<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Minecraft Addon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#value</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.json</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.json</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.json</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.json</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.json</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.json</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.json</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.json</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.json</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.json</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.js</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(?:true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.json</string>
		</dict>
		<key>mcaddon</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.json</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.json</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>UI Inherit Type</string>
					<key>match</key>
					<string>(?&lt;=\.)([a-zA-Z0-9_]+)(?=\")</string>
					<key>name</key>
					<string>support.function.uitype.mcaddon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-)?\d+(\.\d+)?(\%)?(c|x|px)?(?=[\"\s-+])</string>
					<key>name</key>
					<string>constant.numeric.json</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Minecraft Keyword</string>
					<key>match</key>
					<string>(\b(minecraft)\b)</string>
					<key>name</key>
					<string>keyword.other.minecraft.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Minecraft Keyword</string>
					<key>match</key>
					<string>(\b(format_version)\b)</string>
					<key>name</key>
					<string>keyword.other.formatversion.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Minecraft Object Parameter</string>
					<key>match</key>
					<string>(?&lt;=minecraft:)([^"]+)(?=")(?!"\s*[,\n])</string>
					<key>name</key>
					<string>entity.name.minecraftParam.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Minecraft Object Parameter</string>
					<key>match</key>
					<string>(?&lt;=minecraft:)([0-9a-zA-Z_\.]+)</string>
					<key>name</key>
					<string>variable.parameter.minecraftParam.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Invalid Minecraft Parameter</string>
					<key>match</key>
					<string>(?&lt;=minecraft:)([0-9a-zA-Z_\.]+(?!["]))</string>
					<key>name</key>
					<string>invalid.illegal.minecraft.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Definitions</string>
					<key>match</key>
					<string>(\b(items|family)\b)</string>
					<key>name</key>
					<string>support.function.definition.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Definitions</string>
					<key>match</key>
					<string>(\b(and|not|or)\b)</string>
					<key>name</key>
					<string>keyword.control.uilogic.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Definition</string>
					<key>match</key>
					<string>(?&lt;=\")([a-zA-Z0-9_]+)(?=\@)</string>
					<key>name</key>
					<string>keyword.other.uidefinition.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Controls</string>
					<key>match</key>
					<string>([@$#|])</string>
					<key>name</key>
					<string>constant.numeric.uicontrol.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Parenthesis</string>
					<key>match</key>
					<string>([\(\)])</string>
					<key>name</key>
					<string>meta.parenthesis.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Hyperlink</string>
					<key>match</key>
					<string>(http|www)[^"]+</string>
					<key>name</key>
					<string>meta.hyperlink.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>File Path</string>
					<key>match</key>
					<string>(([a-zA-Z0-9_]+)\/)+[a-zA-Z0-9_\.]+</string>
					<key>name</key>
					<string>meta.filepath.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Namespace</string>
					<key>match</key>
					<string>(\bnamespace\b)</string>
					<key>name</key>
					<string>keyword.other.uinamespace</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Namespace Type</string>
					<key>match</key>
					<string>(?&lt;=\@)([a-zA-Z0-9_]+)(?=[\.\"])</string>
					<key>name</key>
					<string>entity.name.namespae.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Variable</string>
					<key>match</key>
					<string>(?&lt;=\$)([a-zA-Z0-9_]+)</string>
					<key>name</key>
					<string>entity.name.uivar.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Type</string>
					<key>match</key>
					<string>(?&lt;=\#)([a-zA-Z0-9_]+)</string>
					<key>name</key>
					<string>variable.parameter.uitype.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UI Default</string>
					<key>match</key>
					<string>(?&lt;=\|)(\b(default)\b)</string>
					<key>name</key>
					<string>keyword.other.uidefault.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Event Functions</string>
					<key>match</key>
					<string>(\b(randomize|add|remove|sequence)\b)</string>
					<key>name</key>
					<string>support.function.eventFunction.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Loot Functions</string>
					<key>match</key>
					<string>(\b(functions|levels|count|rolls)\b)</string>
					<key>name</key>
					<string>support.function.loot.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Trade Parameters</string>
					<key>match</key>
					<string>(\b(wants|gives|quantity)\b)</string>
					<key>name</key>
					<string>support.function.trades.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Item Definitions</string>
					<key>match</key>
					<string>(\b(effects|enchanted_effects|food|seed)\b)</string>
					<key>name</key>
					<string>support.function.items.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Item camera definition</string>
					<key>match</key>
					<string>(?&lt;=")(camera)(?="\s*:)</string>
					<key>name</key>
					<string>support.function.items.camera.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Components and Component Groups</string>
					<key>match</key>
					<string>(\b(component(s|_groups)\b))</string>
					<key>name</key>
					<string>keyword.control.components.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Trade Object Definitions</string>
					<key>match</key>
					<string>(\b(pools|entries|function|tiers|trades)\b)</string>
					<key>name</key>
					<string>entity.name.stuff.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Entity type</string>
					<key>match</key>
					<string>(\b(entity_types)\b)</string>
					<key>name</key>
					<string>entity.name.section.entityType.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Filters</string>
					<key>match</key>
					<string>(\b(filters)\b)</string>
					<key>name</key>
					<string>entity.name.section.filter.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Event keyword</string>
					<key>match</key>
					<string>(\b(event)\b)</string>
					<key>name</key>
					<string>entity.name.type.events.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Events keyword</string>
					<key>match</key>
					<string>(\b(events)\b)</string>
					<key>name</key>
					<string>keyword.control.events.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Json File Path</string>
					<key>match</key>
					<string>(?i)(?&lt;=")[a-zA-Z0-9_/\\\.]+\.(json)(?=")</string>
					<key>name</key>
					<string>variable.other.filepath.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Array Definition</string>
					<key>match</key>
					<string>(?&lt;=")([a-zA-Z0-9_:\+]+)(?="\s*:\s*\[)</string>
					<key>name</key>
					<string>storage.type.arrayDefinition.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Object Definition</string>
					<key>match</key>
					<string>(?&lt;=")([a-zA-Z0-9_:\+]+)(?="\s*:\s*\{)</string>
					<key>name</key>
					<string>entity.name.objectDefinition.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Object Parameters</string>
					<key>match</key>
					<string>(?&lt;=\")([^"])+(?=\" *\:)</string>
					<key>name</key>
					<string>variable.parameter.object.mcaddon</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Strings</string>
					<key>match</key>
					<string>(?&lt;=\")[^"]+(?=")</string>
					<key>name</key>
					<string>string.quoted.double.mcaddon</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?x)        # turn on extended mode
-?        # an optional minus
(?:
  0       # a zero
  |       # ...or...
  [1-9]   # a 1-9 character
  \d*     # followed by zero or more digits
)
(?:
  (?:
    \.    # a period
    \d+   # followed by one or more digits
  )?
  (?:
    [eE]  # an e character
    [+-]? # followed by an option +/-
    \d+   # followed by one or more digits
  )?      # make exponent optional
  (?:
    (px|%(c|x)?)  # % or px
  )? 
)?        # make decimal portion optional</string>
			<key>name</key>
			<string>constant.numeric.json</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.json</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.json</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dictionary.json</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>the JSON object key</string>
					<key>include</key>
					<string>#mcaddon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.key-value.json</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(,)|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.pair.json</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.dictionary.value.json</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>the JSON object value</string>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s,]</string>
							<key>name</key>
							<string>invalid.illegal.expected-dictionary-separator.json</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\}]</string>
					<key>name</key>
					<string>invalid.illegal.expected-dictionary-separator.json</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mcaddon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mcaddon</string>
	<key>uuid</key>
	<string>a0c7e4ae-079d-4d09-9b1d-5379c586f67a</string>
</dict>
</plist>
